package com.example.hexagonalorders.infrastructure.in.web.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for Order data.
 * This class is used to transfer order data between the adapter layer
 * and the application layer, keeping the domain model isolated.
 */
@Data
public class OrderDto {
    @Schema(description = "Technical identifier of the order. Generated by the backend.", example = "123", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Business order number. Generated by the backend.", example = "ORD-20240618-001", accessMode = Schema.AccessMode.READ_ONLY)
    private String orderNumber;

    @Schema(description = "Customer identifier.", example = "CUST-001", required = true)
    private String customerId;

    @Schema(description = "Order creation date.", example = "2024-06-18T10:00:00", required = true)
    private LocalDateTime orderDate;

    @Schema(description = "List of order items.", required = true)
    private List<OrderItemDto> items;

    @Schema(description = "Order status.", example = "CREATED", required = true)
    private String status;

    public OrderDto() {}

    public OrderDto(String orderNumber, String customerId, LocalDateTime orderDate, List<OrderItemDto> items, String status) {
        this.orderNumber = orderNumber;
        this.customerId = customerId;
        this.orderDate = orderDate;
        this.items = items;
        this.status = status;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public String getCustomerId() {
        return customerId;
    }
    
    public LocalDateTime getOrderDate() {
        return orderDate;
    }
    
    public List<OrderItemDto> getItems() {
        return items;
    }
    
    public String getStatus() {
        return status;
    }
} 