package com.example.hexagonalorders.infrastructure.in.web.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Data Transfer Object for Order data.
 * This class is used to transfer order data between the adapter layer
 * and the application layer, keeping the domain model isolated.
 */
@Data
public class OrderDto {
    @Schema(description = "Technical identifier of the order. Generated by the backend.", example = "123", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Business order number. Generated by the backend.", example = "ORD-20240618-001", accessMode = Schema.AccessMode.READ_ONLY)
    private String orderNumber;

    @Schema(description = "Customer identifier.", example = "CUST-001", required = true)
    private String customerId;

    @Schema(description = "Order creation date.", example = "2024-06-18T10:00:00", required = true)
    private LocalDateTime orderDate;

    @Schema(description = "List of order items.", required = true)
    private List<OrderItemDto> items;

    @Schema(description = "Order status.", example = "PENDING", required = true)
    private String status;

    @Schema(description = "Street address for shipping.", example = "123 Main St", required = true)
    private String street;
    @Schema(description = "City for shipping.", example = "Springfield", required = true)
    private String city;
    @Schema(description = "State or province for shipping.", example = "IL", required = true)
    private String state;
    @Schema(description = "Postal code for shipping.", example = "62704", required = true)
    private String postalCode;
    @Schema(description = "Country for shipping.", example = "USA", required = true)
    private String country;

    public OrderDto() {}

    public OrderDto(String orderNumber, String customerId, LocalDateTime orderDate, List<OrderItemDto> items, String status) {
        this.orderNumber = orderNumber;
        this.customerId = customerId;
        this.orderDate = orderDate;
        this.items = items;
        this.status = status;
    }

    public String getCustomerId() {
        return customerId;
    }
    public LocalDateTime getOrderDate() {
        return orderDate;
    }
    public String getStatus() {
        return status;
    }

    public String getStreet() { return street; }
    public void setStreet(String street) { this.street = street; }
    public String getCity() { return city; }
    public void setCity(String city) { this.city = city; }
    public String getState() { return state; }
    public void setState(String state) { this.state = state; }
    public String getPostalCode() { return postalCode; }
    public void setPostalCode(String postalCode) { this.postalCode = postalCode; }
    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }
} 